# Generated by Django 5.2.4 on 2026-07-22 11:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='professional_headline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.job_seeker_resume_path),
        ),
    ]
