import {ArrowLeft,Download,FileText,Mail,MapPin,Phone} from "lucide-react";
import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import InterviewWorkflow from "../components/InterviewWorkflow";
import api,{errorMessage} from "../services/api";
import {useAuth} from "../state/AuthContext";

export default function ApplicationDetailPage(){
  const {id}=useParams();const {user}=useAuth();const [item,setItem]=useState(null);const [message,setMessage]=useState("");
  async function load(){try{const {data}=await api.get(`/applications/${id}/`);setItem(data)}catch(e){setMessage(errorMessage(e))}}
  useEffect(()=>{load()},[id]);
  async function withdraw(){if(!confirm("Withdraw this application?"))return;try{const {data}=await api.post(`/applications/${id}/withdraw/`);setItem(data)}catch(e){setMessage(errorMessage(e))}}
  async function download(doc){const response=await api.get(doc.download_url,{responseType:"blob"});const url=URL.createObjectURL(response.data);const link=document.createElement("a");link.href=url;link.download="cv.pdf";link.click();URL.revokeObjectURL(url)}
  async function replace(e){const file=e.target.files[0];if(!file)return;const form=new FormData();form.append("file",file);form.append("label","CV");try{await api.put(`/applications/${id}/cv/`,form);await load();setMessage("CV updated successfully.")}catch(e){setMessage(errorMessage(e))}}
  if(!item)return <div className="card empty">{message||"Loading application…"}</div>;
  return <article className="application-detail"><Link to={user.role==="employer"?"/applicants":"/applications"} className="back"><ArrowLeft/>Back</Link><header><div><small>Application reference</small><h1>{item.reference}</h1><p>{item.job_title}</p></div><span className={`status ${item.status}`}>{item.status}</span></header>{message&&<div className="alert">{message}</div>}{user.role==="employer"&&<section><h2>Applicant</h2><div className="detail-applicant"><div className="applicant-identity">{item.applicant_avatar?<img src={item.applicant_avatar} alt=""/>:<span>{item.applicant_name?.[0]}</span>}<div><h3>{item.applicant_name}</h3>{item.applicant_profile?.skills&&<small>{item.applicant_profile.skills}</small>}</div></div><div className="candidate-contact"><a href={`mailto:${item.applicant_email}`}><Mail/>{item.applicant_email}</a>{item.applicant_phone&&<a href={`tel:${item.applicant_phone}`}><Phone/>{item.applicant_phone}</a>}{item.applicant_profile?.city&&<span><MapPin/>{item.applicant_profile.city}, {item.applicant_profile.province}</span>}</div>{item.applicant_profile?.bio&&<p>{item.applicant_profile.bio}</p>}</div></section>}<InterviewWorkflow application={item} user={user} onApplicationChanged={load}/><section><h2>Status history</h2><div className="timeline">{item.status_history.map(event=><div className="timeline-event" key={event.id}><i/><div><b>{event.to_status}</b><p>{event.message}</p><small>{new Date(event.created_at).toLocaleString("en-ZA")} · {event.changed_by_name}</small></div></div>)}</div></section><section><h2>Documents</h2>{item.documents.length?item.documents.map(doc=><button className="document-row" onClick={()=>download(doc)} key={doc.id}><Download/>{doc.label}</button>):<p>No CV attached.</p>}{user.role==="job_seeker"&&item.status!=="withdrawn"&&<label className="replace-cv"><FileText/>Attach or replace CV<input type="file" accept="application/pdf" onChange={replace}/></label>}</section>{user.role==="job_seeker"&&!['withdrawn','hired'].includes(item.status)&&<button className="button danger" onClick={withdraw}>Withdraw application</button>}</article>
}
