import {CalendarClock,Download,Eye,Mail,MapPin,Phone} from "lucide-react";
import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import api,{errorMessage} from "../services/api";
import {useAuth} from "../state/AuthContext";

const statuses=["submitted","reviewing","shortlisted","interview","unsuccessful","hired"];
export default function ApplicantsPage(){
  const {user}=useAuth();const [items,setItems]=useState([]);const [interviews,setInterviews]=useState([]);const [error,setError]=useState("");
  async function load(){if(user?.role!=="employer")return;try{const [applications,meetings]=await Promise.all([api.get("/applications/"),api.get("/interviews/")]);setItems(applications.data.results||applications.data);setInterviews(meetings.data.results||meetings.data)}catch(e){setError(errorMessage(e))}}
  useEffect(()=>{load()},[user]);
  async function update(id,status){const message=prompt("Optional message to the applicant:")||"";try{await api.patch(`/applications/${id}/status/`,{status,message});await load()}catch(e){setError(errorMessage(e))}}
  async function download(doc){const response=await api.get(doc.download_url,{responseType:"blob"});const url=URL.createObjectURL(response.data);const link=document.createElement("a");link.href=url;link.download="candidate-cv.pdf";link.click();URL.revokeObjectURL(url)}
  if(user?.role!=="employer")return <div className="card empty">This page is for employers.</div>;
  return <><div className="dashboard-heading"><div><h1>Applicants</h1><p>Review candidates, schedule interviews and keep every decision traceable.</p></div><Link className="button ghost" to="/interviews"><CalendarClock/>Interview Hub</Link></div>{error&&<div className="alert error">{error}</div>}{items.length?items.map(item=>{const meeting=interviews.filter(i=>Number(i.application)===Number(item.id)).sort((a,b)=>new Date(b.scheduled_start)-new Date(a.scheduled_start))[0];return <article className="applicant-card" key={item.id}><header><div className="applicant-identity">{item.applicant_avatar?<img src={item.applicant_avatar} alt=""/>:<span>{item.applicant_name?.[0]}</span>}<div><h2>{item.applicant_name}</h2><b>{item.job_title}</b><small>{item.reference}</small></div></div><select aria-label="Application status" value={item.status} onChange={e=>update(item.id,e.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></header><div className="candidate-contact"><a href={`mailto:${item.applicant_email}`}><Mail/>{item.applicant_email}</a>{item.applicant_phone&&<a href={`tel:${item.applicant_phone}`}><Phone/>{item.applicant_phone}</a>}{item.applicant_profile?.city&&<span><MapPin/>{item.applicant_profile.city}, {item.applicant_profile.province}</span>}</div>{meeting&&<div className="applicant-interview-summary"><CalendarClock/><div><b>{meeting.title}</b><span>{new Date(meeting.scheduled_start).toLocaleString("en-ZA")} · {meeting.candidate_response.replaceAll("_"," ")}</span></div></div>}{item.applicant_profile?.skills&&<p><b>Skills:</b> {item.applicant_profile.skills}</p>}<div className="documents">{item.documents.map(doc=><button key={doc.id} onClick={()=>download(doc)}><Download/>{doc.label||"Document"}</button>)}<Link className="button primary" to={`/applications/${item.id}`}><Eye/>{meeting?"Manage interview":"Review and interview"}</Link></div></article>}):<div className="card empty">No applications received yet.</div>}</>
}
