import { FileText, Image, Upload, Video } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import api, {errorMessage} from "../services/api";
import { useAuth } from "../state/AuthContext";
export default function PostJobPage() {
  const {user} = useAuth(); const navigate = useNavigate(); const [files, setFiles] = useState([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  if (user?.role !== "employer") return <div className="card empty">Only employer accounts can post jobs.</div>;
  async function submit(e) { e.preventDefault(); setSaving(true); setError(""); try { const payload = Object.fromEntries(new FormData(e.currentTarget)); Object.keys(payload).forEach(key => payload[key] === "" && delete payload[key]); const {data: job} = await api.post("/jobs/", payload); for (const file of files) { const media = new FormData(); media.append("file", file); await api.post(`/jobs/${job.id}/media/`, media, {headers:{"Content-Type":"multipart/form-data"}}); } navigate("/employer"); } catch(e) { setError(errorMessage(e)); } finally { setSaving(false); } }
  return <div className="form-card"><h1>Post an opportunity</h1><p>Keep it clear, honest and easy to understand.</p>{error && <div className="alert error">{error}</div>}<form className="form-grid" onSubmit={submit}><label className="span-2">Job title<input name="title" required placeholder="e.g. Delivery Driver"/></label><label>Category<input name="category" required placeholder="Transport"/></label><label>Employment type<select name="employment_type"><option value="permanent">Permanent</option><option value="contract">Contract</option><option value="temporary">Temporary</option><option value="part_time">Part-time</option><option value="internship">Internship</option></select></label><label>Province<input name="province" required/></label><label>City or town<input name="city" required/></label><label>Workplace<select name="workplace"><option value="onsite">On-site</option><option value="hybrid">Hybrid</option><option value="remote">Remote</option></select></label><label>Closing date<input type="date" name="closing_date" required/></label><label>Positions available<input type="number" name="positions_available" min="1" defaultValue="1"/></label><label className="checkbox"><input type="checkbox" name="urgent" value="true"/>Urgent opportunity</label><label className="span-2">Description<textarea name="description" rows="6" required/></label><label className="span-2">Requirements<textarea name="requirements" rows="4"/></label><label>Minimum salary<input type="number" name="salary_min" min="0"/></label><label>Maximum salary<input type="number" name="salary_max" min="0"/></label><div className="upload-box span-2"><Upload/><b>Add supporting media</b><p>Images up to 8 MB, videos up to 50 MB, PDFs up to 10 MB.</p><div className="media-types"><span><Image/>JPG, PNG, WebP</span><span><Video/>MP4, WebM</span><span><FileText/>PDF</span></div><input type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,application/pdf" onChange={e => setFiles([...e.target.files])}/>{files.map(file=><small key={file.name}>{file.name}</small>)}</div><button className="button primary span-2" disabled={saving}>{saving ? "Submitting…" : "Submit for review"}</button></form></div>;
}
