import {Camera,UserRound} from "lucide-react";
import {useEffect,useState} from "react";
import api,{errorMessage,mediaUrl} from "../services/api";
import {useAuth} from "../state/AuthContext";

export default function ProfilePage(){
  const {user,updateUser}=useAuth();const [profile,setProfile]=useState(null);const [message,setMessage]=useState("");const [preview,setPreview]=useState(mediaUrl(user.avatar));
  useEffect(()=>{api.get("/auth/profile/").then(({data})=>setProfile(data)).catch(e=>setMessage(errorMessage(e)));},[]);
  async function submit(e){e.preventDefault();setMessage("");try{const raw=new FormData(e.currentTarget);const avatar=raw.get("avatar");const avatarChanged=Boolean(avatar?.size);const userForm=new FormData();["first_name","last_name","phone"].forEach(key=>userForm.append(key,raw.get(key)||""));if(avatarChanged)userForm.append("avatar",avatar);const profilePayload=Object.fromEntries([...raw.entries()].filter(([key])=>!["first_name","last_name","phone","avatar"].includes(key)));const profileResult=await api.patch("/auth/profile/",profilePayload);const userResult=await api.patch("/auth/me/",userForm);setProfile(profileResult.data);updateUser(userResult.data,{avatarChanged});const savedAvatar=mediaUrl(userResult.data.avatar,avatarChanged?Date.now():null);setPreview(savedAvatar);setMessage("Profile updated successfully.");}catch(e){setMessage(errorMessage(e));}}
  function choose(e){const file=e.target.files[0];if(file)setPreview(URL.createObjectURL(file));}
  if(!profile)return <div className="card empty">{message||"Loading profile…"}</div>;
  const employer=user.role==="employer";const initials=`${user.first_name?.[0]||user.username?.[0]||"U"}${user.last_name?.[0]||""}`.toUpperCase();
  return <div className="form-card"><div className="profile-heading"><div><h1>Your profile</h1><p>{employer?"A recognisable organisation image and complete details build trust.":"Your photo is optional and is shown only to employers you apply to."}</p></div>{employer&&<span className={`verification ${profile.is_verified?"verified-profile":""}`}>{profile.is_verified?"✓ Verified employer":"Verification pending"}</span>}</div>{message&&<div className="alert">{message}</div>}<form className="form-grid" onSubmit={submit}><div className="avatar-editor span-2">{preview?<img src={preview} alt="Profile preview"/>:<span>{initials}</span>}<label><Camera/>Choose {employer?"organisation image":"profile picture"}<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/></label><small>Optional JPG, PNG or WebP. Maximum 3 MB.</small></div><label>First name<input name="first_name" defaultValue={user.first_name}/></label><label>Last name<input name="last_name" defaultValue={user.last_name}/></label><label>Phone<input name="phone" defaultValue={user.phone}/></label>{employer?<><label className="span-2">Organisation name<input name="organisation_name" defaultValue={profile.organisation_name} required/></label><label>Registration number<input name="registration_number" defaultValue={profile.registration_number}/></label><label>Website<input name="website" type="url" defaultValue={profile.website}/></label><label className="span-2">About the organisation<textarea name="description" rows="5" defaultValue={profile.description}/></label></>:<><label>Province<input name="province" defaultValue={profile.province}/></label><label>City or town<input name="city" defaultValue={profile.city}/></label><label className="span-2">Skills<input name="skills" defaultValue={profile.skills} placeholder="Driving, customer service, stock control"/></label><label>Availability<input name="availability" defaultValue={profile.availability} placeholder="Immediately available"/></label><label className="span-2">Short introduction<textarea name="bio" rows="5" defaultValue={profile.bio}/></label></>}<button className="button primary span-2">Save profile</button></form></div>;
}
