# Generated by Django 5.2.4 on 2026-07-17 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_reference_application_sharing_consent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatushistory',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('employer', 'Employer'), ('job_seeker', 'Job seeker'), ('admin', 'Administrator'), ('system', 'System')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('part_time', 'Part-time'), ('internship', 'Internship')], max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending confirmation'), ('employer_confirmed', 'Employer confirmed'), ('seeker_confirmed', 'Job seeker confirmed'), ('confirmed', 'Confirmed by both parties'), ('disputed', 'Disputed'), ('unable_to_verify', 'Unable to verify'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('verification_method', models.CharField(blank=True, choices=[('in_app', 'In-app confirmation'), ('admin_review', 'Administrator review'), ('document', 'Supporting document')], max_length=20)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('ending_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='placement', to='jobs.application')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlacementConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_role', models.CharField(choices=[('employer', 'Employer'), ('job_seeker', 'Job seeker')], max_length=20)),
                ('response', models.CharField(choices=[('started', 'Started employment'), ('accepted_not_started', 'Accepted but not started'), ('did_not_accept', 'Did not accept'), ('information_incorrect', 'Information is incorrect'), ('no_longer_employed', 'No longer employed'), ('prefer_not_to_answer', 'Prefer not to answer')], max_length=24)),
                ('confirmed_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='jobs.placement')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('responded_at',),
            },
        ),
        migrations.CreateModel(
            name='PlacementFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('30_day', '30-day follow-up'), ('90_day', '90-day follow-up')], max_length=10)),
                ('due_date', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('still_employed', 'Still employed'), ('ended', 'Employment ended'), ('unknown', 'Unknown'), ('prefer_not_to_answer', 'Prefer not to answer')], default='unknown', max_length=24)),
                ('respondent_role', models.CharField(blank=True, choices=[('employer', 'Employer'), ('job_seeker', 'Job seeker')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='jobs.placement')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='PlacementResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pending confirmation'), ('employer_confirmed', 'Employer confirmed'), ('seeker_confirmed', 'Job seeker confirmed'), ('confirmed', 'Confirmed by both parties'), ('disputed', 'Disputed'), ('unable_to_verify', 'Unable to verify'), ('cancelled', 'Cancelled')], max_length=24)),
                ('resolved_status', models.CharField(choices=[('pending', 'Pending confirmation'), ('employer_confirmed', 'Employer confirmed'), ('seeker_confirmed', 'Job seeker confirmed'), ('confirmed', 'Confirmed by both parties'), ('disputed', 'Disputed'), ('unable_to_verify', 'Unable to verify'), ('cancelled', 'Cancelled')], max_length=24)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='jobs.placement')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['verification_status', 'actual_start_date'], name='jobs_placem_verific_a59950_idx'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.CheckConstraint(condition=models.Q(('actual_start_date__isnull', True), ('ended_at__isnull', True), ('ended_at__gte', models.F('actual_start_date')), _connector='OR'), name='placement_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='placementconfirmation',
            constraint=models.UniqueConstraint(fields=('placement', 'respondent_role'), name='one_placement_confirmation_per_party'),
        ),
        migrations.AddConstraint(
            model_name='placementfollowup',
            constraint=models.UniqueConstraint(fields=('placement', 'follow_up_type'), name='one_follow_up_type_per_placement'),
        ),
    ]
