# Generated by Django 5.2.4 on 2026-07-17 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_applicationstatushistory_actor_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address_visibility',
            field=models.CharField(choices=[('exact', 'Show exact address'), ('area_only', 'Show area only'), ('approximate', 'Show approximate area'), ('shortlisted', 'Share after shortlisting'), ('hidden', 'Do not display')], default='area_only', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_confirmed_by_employer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_precision',
            field=models.CharField(choices=[('province', 'Province'), ('district', 'District'), ('town', 'Town or city'), ('suburb', 'Suburb, township or village'), ('street', 'Street'), ('exact', 'Exact address')], default='town', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='location_review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed'), ('needs_changes', 'Needs changes')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='location_verified_by_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='municipality',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='public_location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='street_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='street_view_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='suburb',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='JobLocationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_area', 'Pin is in the wrong area'), ('address_mismatch', 'Address does not match the description'), ('unsafe_or_suspicious', 'Location appears unsafe or suspicious'), ('workplace_not_found', 'Workplace does not exist'), ('private_address_exposed', 'A private address is exposed'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_reports', to='jobs.job')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_location_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
