import {CalendarClock, CheckCircle2, ExternalLink, RotateCcw, Video, XCircle} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import api,{errorMessage} from "../services/api";

const providers=[["zoom","Zoom"],["google_meet","Google Meet"],["microsoft_teams","Microsoft Teams"],["whatsapp","WhatsApp"],["jitsi","UmsebenziWethu Live / Jitsi"],["external","Other provider"]];
const activeStatuses=["submitted","reviewing","shortlisted","interview"];
const local=value=>new Date(value).toLocaleString("en-ZA",{dateStyle:"medium",timeStyle:"short"});
const rows=data=>data.results||data;
const initialStart=()=>{const date=new Date(Date.now()+86400000);date.setMinutes(0,0,0);return date.toISOString().slice(0,16)};

function InterviewForm({applicationId,existing,onSaved,onClose}){
  const duration=existing?Math.max(10,Math.round((new Date(existing.scheduled_end)-new Date(existing.scheduled_start))/60000)):30;
  const [form,setForm]=useState({application:applicationId,provider:existing?.provider||"zoom",title:existing?.title||"Job interview",scheduled_start:existing?new Date(existing.scheduled_start).toISOString().slice(0,16):initialStart(),duration,join_url:"",host_url:"",instructions:existing?.instructions||"Please join five minutes early.",recording_allowed:false});
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const change=e=>setForm({...form,[e.target.name]:e.target.value});
  async function submit(e){e.preventDefault();setBusy(true);setError("");try{const start=new Date(form.scheduled_start);const payload={application:Number(applicationId),provider:form.provider,title:form.title,scheduled_start:start.toISOString(),scheduled_end:new Date(start.getTime()+Number(form.duration)*60000).toISOString(),timezone_name:"Africa/Johannesburg",instructions:form.instructions,recording_allowed:false};if(form.join_url)payload.join_url=form.join_url;if(form.host_url)payload.host_url=form.host_url;if(existing)await api.patch(`/interviews/${existing.id}/`,payload);else await api.post("/interviews/",payload);onSaved();}catch(e){setError(errorMessage(e));}finally{setBusy(false)}}
  return <form className="interview-form" onSubmit={submit}><div className="section-heading"><div><h3>{existing?"Reschedule interview":"Schedule interview"}</h3><p>{existing?"The original event remains in the audit history.":"Send a protected invitation linked to this application."}</p></div>{onClose&&<button type="button" className="icon-button" onClick={onClose} aria-label="Close"><XCircle/></button>}</div>{error&&<div className="alert error">{error}</div>}<div className="interview-form-grid"><label>Interview title<input required name="title" value={form.title} onChange={change}/></label><label>Provider<select name="provider" value={form.provider} onChange={change}>{providers.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Starting time<input required type="datetime-local" name="scheduled_start" value={form.scheduled_start} onChange={change}/></label><label>Duration in minutes<input required type="number" min="10" max="240" name="duration" value={form.duration} onChange={change}/></label><label className="span-2">Candidate meeting link<input required={!existing} type="url" name="join_url" value={form.join_url} onChange={change} placeholder={existing?"Leave blank to keep the current protected link":"https://…"}/></label><label className="span-2">Private host link (optional)<input type="url" name="host_url" value={form.host_url} onChange={change} placeholder="Never shown to the applicant"/></label><label className="span-2">Instructions<textarea name="instructions" value={form.instructions} onChange={change}/></label></div><div className="privacy-strip">Recording is disabled for the pilot. Candidate meeting links are returned only during the permitted joining window.</div><div className="form-actions"><button className="button primary" disabled={busy}>{busy?"Saving…":existing?"Save new time":"Send invitation"}</button>{onClose&&<button type="button" className="button ghost" onClick={onClose}>Cancel</button>}</div></form>
}

function EventTimeline({events=[]}){return <details className="event-history"><summary>Activity history ({events.length})</summary>{events.map(event=><div className="event-row" key={event.id}><i/><div><b>{event.event_type.replaceAll("_"," ")}</b>{event.note&&<p>{event.note}</p>}<small>{local(event.created_at)} · {event.actor_name}</small></div></div>)}</details>}

function interviewPresentation(interview){
  const now=new Date();const start=new Date(interview.scheduled_start);const end=new Date(interview.scheduled_end);
  if(interview.status==="scheduled"&&now>end&&interview.candidate_response==="pending")return{title:"Invitation expired without response",description:"The scheduled time passed without an applicant response.",applicantResponse:"No response received",interviewOutcome:"Not yet recorded",tone:"warning"};
  if(interview.status==="scheduled"&&now>end)return{title:"Interview outcome overdue",description:"The scheduled time passed, but the outcome has not been recorded.",applicantResponse:interview.candidate_response==="accepted"?"Attendance confirmed":interview.candidate_response.replaceAll("_"," "),interviewOutcome:"Not yet recorded",tone:"warning"};
  if(interview.status==="scheduled"&&now>=start&&now<=end)return{title:"Interview joining window open",description:"The interview is currently within its scheduled time.",applicantResponse:interview.candidate_response==="accepted"?"Attendance confirmed":"Not confirmed",interviewOutcome:"In progress",tone:"active"};
  if(interview.status==="scheduled"&&interview.candidate_response==="accepted")return{title:"Interview confirmed",description:"The applicant accepted this interview.",applicantResponse:"Attendance confirmed",interviewOutcome:"Upcoming",tone:"success"};
  return{title:interview.status.replaceAll("_"," "),description:"",applicantResponse:interview.candidate_response==="pending"?"Awaiting applicant response":interview.candidate_response.replaceAll("_"," "),interviewOutcome:interview.status==="scheduled"?"Upcoming":interview.status.replaceAll("_"," "),tone:"neutral"};
}

function sastDate(value){return new Date(value).toLocaleString("en-ZA",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Johannesburg"})}

export function InterviewCard({item,role,onChanged}){
  const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function candidateResponse(response){let note="";if(response==="reschedule")note=prompt("What time or arrangement would work better?")||"";setBusy(true);try{await api.post(`/interviews/${item.id}/respond/`,{response,note});onChanged();}catch(e){setError(errorMessage(e));}finally{setBusy(false)}}
  async function join(){setBusy(true);try{const {data}=await api.post(`/interviews/${item.id}/join/`);window.open(data.meeting_url,"_blank","noopener,noreferrer");onChanged();}catch(e){setError(errorMessage(e));}finally{setBusy(false)}}
  async function outcome(status){const note=prompt("Optional factual note about the interview:")||"";setBusy(true);try{await api.post(`/interviews/${item.id}/outcome/`,{status,note});onChanged();}catch(e){setError(errorMessage(e));}finally{setBusy(false)}}
  const presentation=interviewPresentation(item);
  return <article className="interview-card"><header><span className="meeting-symbol"><Video/></span><div><small>{item.provider.replaceAll("_"," ")} · {item.application_reference}</small><h3>{item.title}</h3><p>{item.job_title} · {item.organisation_name}</p>{role==="employer"&&<p>Candidate: <b>{item.candidate_name}</b></p>}</div><span className={`status ${presentation.tone}`}>{presentation.title}</span></header><div className={`interview-state ${presentation.tone}`}><strong>{presentation.title}</strong>{presentation.description&&<p>{presentation.description}</p>}</div><div className="interview-facts"><span><CalendarClock/>Scheduled: <b>{sastDate(item.scheduled_start)}–{sastDate(item.scheduled_end)} SAST</b></span><span>Duration: {Math.round((new Date(item.scheduled_end)-new Date(item.scheduled_start))/60000)} minutes</span><span>Applicant response: <b>{presentation.applicantResponse}</b></span><span>Interview outcome: <b>{presentation.interviewOutcome}</b></span></div>{item.instructions&&<p className="instructions">{item.instructions}</p>}{error&&<div className="alert error">{error}</div>}<div className="interview-actions">{role==="job_seeker"&&item.status==="scheduled"&&item.candidate_response==="pending"&&new Date()<=new Date(item.scheduled_end)&&<><button disabled={busy} className="button primary" onClick={()=>candidateResponse("accepted")}><CheckCircle2/>Accept</button><button disabled={busy} className="button ghost" onClick={()=>candidateResponse("reschedule")}><RotateCcw/>Request another time</button><button disabled={busy} className="text-danger" onClick={()=>candidateResponse("declined")}>Decline</button></>}{item.can_join&&<button disabled={busy} className="button primary" onClick={join}><ExternalLink/>Join interview</button>}{role==="employer"&&["scheduled","reschedule_requested"].includes(item.status)&&<><button className="button ghost" onClick={()=>setEditing(!editing)}><RotateCcw/>Reschedule</button><button className="button ghost" onClick={()=>outcome("cancelled")}>Cancel interview</button></>}{role==="employer"&&item.status==="scheduled"&&<div className="outcome-menu"><span>{new Date()>new Date(item.scheduled_end)?"Outcome required:":"After the meeting:"}</span><button onClick={()=>outcome("completed")}>Completed</button><button onClick={()=>outcome("candidate_no_show")}>Candidate no-show</button><button onClick={()=>outcome("employer_no_show")}>Employer no-show</button><button onClick={()=>outcome("technical_failure")}>Technical failure</button></div>}</div>{editing&&<InterviewForm applicationId={item.application} existing={item} onSaved={()=>{setEditing(false);onChanged()}} onClose={()=>setEditing(false)}/>}<EventTimeline events={item.events}/></article>
}

export default function InterviewWorkflow({application,user,onApplicationChanged}){
  const [items,setItems]=useState([]);const [showForm,setShowForm]=useState(false);const [message,setMessage]=useState("");const [sessions,setSessions]=useState([]);const [selectedSession,setSelectedSession]=useState("");
  async function load(){try{const {data}=await api.get("/interviews/");setItems(rows(data).filter(item=>Number(item.application)===Number(application.id)));if(user.role==="employer"){const sessionData=await api.get("/recruitment-sessions/");setSessions(rows(sessionData.data).filter(session=>Number(session.job)===Number(application.job)));}}catch(e){setMessage(errorMessage(e))}}
  useEffect(()=>{load()},[application.id,user.role]);
  async function decide(status){const note=prompt("Optional message to the applicant:")||"";try{await api.patch(`/applications/${application.id}/status/`,{status,message:note});setMessage(`Application updated to ${status}.`);onApplicationChanged?.();}catch(e){setMessage(errorMessage(e))}}
  async function invite(){if(!selectedSession)return;try{await api.post(`/recruitment-sessions/${selectedSession}/invite/`,{application:application.id});setMessage("Applicant invited to the recruitment session.");await load();}catch(e){setMessage(errorMessage(e))}}
  const upcoming=useMemo(()=>items.filter(i=>["scheduled","reschedule_requested"].includes(i.status)),[items]);
  return <section className="application-interviews"><div className="section-heading"><div><h2>Interviews</h2><p>Schedule, communicate, meet and record the result without losing the application history.</p></div>{user.role==="employer"&&activeStatuses.includes(application.status)&&!showForm&&<button className="button primary" onClick={()=>setShowForm(true)}><CalendarClock/>Schedule interview</button>}</div>{message&&<div className="alert">{message}</div>}{showForm&&<InterviewForm applicationId={application.id} onSaved={()=>{setShowForm(false);load();onApplicationChanged?.()}} onClose={()=>setShowForm(false)}/>}<div className="interview-list">{items.length?items.map(item=><InterviewCard key={item.id} item={item} role={user.role} onChanged={load}/>):<div className="empty-soft">No interview has been scheduled for this application.</div>}</div>{user.role==="employer"&&items.some(i=>i.status==="completed")&&<div className="decision-panel"><h3>Recruitment decision</h3><p>The interview outcome records whether the meeting occurred. Choose the application decision separately.</p><div><button className="button ghost" onClick={()=>decide("reviewing")}>Keep under consideration</button><button className="button ghost" onClick={()=>setShowForm(true)}>Schedule follow-up</button><button className="button danger" onClick={()=>decide("unsuccessful")}>Unsuccessful</button><button className="button primary" onClick={()=>decide("hired")}>Mark hired</button></div></div>}{user.role==="employer"&&sessions.length>0&&<div className="session-invite"><h3>Invite to a recruitment session</h3><div><select value={selectedSession} onChange={e=>setSelectedSession(e.target.value)}><option value="">Choose a session for this job</option>{sessions.map(session=><option value={session.id} key={session.id}>{session.title} · {local(session.scheduled_start)}</option>)}</select><button className="button primary" disabled={!selectedSession} onClick={invite}>Send invitation</button></div></div>}</section>
}
